# Site settings
title: Persian Setar
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Repository of Radif Persian Music 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bamdad.github.io" # the base hostname & protocol for your site
twitter_username: bamdad
github_username:  bamdadd

# Build settings
markdown: kramdown
